In [1]:
import pandas as pd
import numpy as np
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
import mlflow
from mlflow.models import infer_signature

In [2]:
## Set the tracking URI
mlflow.set_tracking_uri(uri = "http://127.0.0.1:5000")

In [3]:
## Load the dataset
X, y = datasets.load_iris(return_X_y=True)


In [4]:
## Splitting the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [5]:
## Define the model hyperparameters
params = {
    "penalty":"l2",
    "solver":"lbfgs",
    "max_iter":1000,
    "multi_class":"auto",
    "random_state":8888,
}

## Train the model

lr = LogisticRegression(**params)
lr.fit(X_train, y_train)


d:\MLOPs\MLFLOW\venv\lib\site-packages\sklearn\linear_model\_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(


LogisticRegression(max_iter=1000, multi_class='auto', random_state=8888)

In [6]:
X_test

array([[6.5, 2.8, 4.6, 1.5],
       [5.9, 3. , 5.1, 1.8],
       [5.7, 3. , 4.2, 1.2],
       [4.6, 3.6, 1. , 0.2],
       [6.2, 2.9, 4.3, 1.3],
       [6. , 3.4, 4.5, 1.6],
       [6.3, 2.3, 4.4, 1.3],
       [5.1, 3.8, 1.5, 0.3],
       [5. , 2. , 3.5, 1. ],
       [6.5, 3.2, 5.1, 2. ],
       [5.7, 4.4, 1.5, 0.4],
       [5.1, 2.5, 3. , 1.1],
       [5.4, 3.4, 1.5, 0.4],
       [5. , 3. , 1.6, 0.2],
       [6.2, 2.8, 4.8, 1.8],
       [5.8, 2.8, 5.1, 2.4],
       [6.8, 3.2, 5.9, 2.3],
       [5.5, 2.4, 3.8, 1.1],
       [7.1, 3. , 5.9, 2.1],
       [5.4, 3.7, 1.5, 0.2],
       [6.7, 3.3, 5.7, 2.1],
       [5.1, 3.5, 1.4, 0.3],
       [6.1, 2.8, 4.7, 1.2],
       [5.5, 2.5, 4. , 1.3],
       [5.7, 2.5, 5. , 2. ],
       [5.4, 3. , 4.5, 1.5],
       [4.9, 2.4, 3.3, 1. ],
       [7.7, 2.8, 6.7, 2. ],
       [5.9, 3. , 4.2, 1.5],
       [6.3, 3.3, 4.7, 1.6]])

In [7]:
## Prediction on the test set 

y_pred = lr.predict(X_test)
print(y_pred)

[1 2 1 0 1 1 1 0 1 2 0 1 0 0 2 2 2 1 2 0 2 0 1 1 2 1 1 2 1 1]


In [8]:
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.2f}")

Accuracy: 1.00


In [9]:
### MLFLOW tracking

mlflow.set_tracking_uri(uri = "http://127.0.0.1:5000")

## Create a new MLflow experiment
mlflow.set_experiment("Iris_Classification")

## Start a MLFlow run and log the model
with mlflow.start_run():
    ## Log the hyperparameters
    mlflow.log_params(params)

    ## log the accuracy metrix
    mlflow.log_metric("accuracy", accuracy)

    ## Set a tag that we can use to remind ourselves what this run was for
    mlflow.set_tag("Training Info", "Basic LR model for Iris Classification")
    
    ## Infer the model signature
    signature = infer_signature(X_train, lr.predict(X_train))

    ## Log the model
    model_info = mlflow.sklearn.log_model(
        sk_model = lr, 
        artifact_path = "Iris_Model",
        signature = signature,
        input_example = X_train,
        registered_model_name = "tracking_iris_model",
    )

Registered model 'tracking_iris_model' already exists. Creating a new version of this model...
2025/04/25 17:15:08 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: tracking_iris_model, version 3


🏃 View run illustrious-shad-629 at: http://127.0.0.1:5000/#/experiments/278257936357084962/runs/840dfbfd09b2439496654a02bbb87ea0
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/278257936357084962


Created version '3' of model 'tracking_iris_model'.


In [10]:
## Define the model hyperparameters
params = {
    "solver":"newton-cg",
    "max_iter":1000,
    "multi_class":"auto",
    "random_state":1000,
}

## Train the model

lr = LogisticRegression(**params)
lr.fit(X_train, y_train)

d:\MLOPs\MLFLOW\venv\lib\site-packages\sklearn\linear_model\_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(


LogisticRegression(max_iter=1000, multi_class='auto', random_state=1000,
                   solver='newton-cg')

In [11]:
## Prediction on the test set 

y_pred = lr.predict(X_test)
print(y_pred)

[1 2 1 0 1 1 1 0 1 2 0 1 0 0 2 2 2 1 2 0 2 0 1 1 2 1 1 2 1 1]


In [12]:
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.2f}")

Accuracy: 1.00


In [13]:
## Start a MLFlow run and log the model
with mlflow.start_run():
    ## Log the hyperparameters
    mlflow.log_params(params)

    ## log the accuracy metrix
    mlflow.log_metric("accuracy", accuracy)

    ## Set a tag that we can use to remind ourselves what this run was for
    mlflow.set_tag("Training Info", "Basic LR model for Iris Classification")
    
    ## Infer the model signature
    signature = infer_signature(X_train, lr.predict(X_train))

    ## Log the model
    model_info = mlflow.sklearn.log_model(
        sk_model = lr, 
        artifact_path = "Iris_Model",
        signature = signature,
        input_example = X_train,
        registered_model_name = "tracking_iris_model",
    )

Registered model 'tracking_iris_model' already exists. Creating a new version of this model...
2025/04/25 17:15:13 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: tracking_iris_model, version 4


🏃 View run fun-hound-506 at: http://127.0.0.1:5000/#/experiments/278257936357084962/runs/46acedda87df49f282a54007de25b35f
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/278257936357084962


Created version '4' of model 'tracking_iris_model'.


## Inferencing and Validating the Model

In [14]:
from mlflow.models import validate_serving_input

model_uri = model_info.model_uri

# The model is logged with an input example. MLflow converts
# it into the serving payload format for the deployed model endpoint,
# and saves it to 'serving_input_payload.json'
serving_payload = """{
  "inputs": [
    [
      5.7,
      3.8,
      1.7,
      0.3
    ],
    [
      4.8,
      3.4,
      1.6,
      0.2
    ],
    [
      5.6,
      2.9,
      3.6,
      1.3
    ],
    [
      5.4,
      3.7,
      1.5,
      0.2
    ],
    [
      6.7,
      3.3,
      5.7,
      2.5
    ],
    [
      6.5,
      3.0,
      5.8,
      2.2
    ],
    [
      5.1,
      2.5,
      3.0,
      1.1
    ],
    [
      7.7,
      3.0,
      6.1,
      2.3
    ],
    [
      5.2,
      4.1,
      1.5,
      0.1
    ],
    [
      5.0,
      3.3,
      1.4,
      0.2
    ],
    [
      4.6,
      3.6,
      1.0,
      0.2
    ],
    [
      4.5,
      2.3,
      1.3,
      0.3
    ],
    [
      5.6,
      2.8,
      4.9,
      2.0
    ],
    [
      6.2,
      3.4,
      5.4,
      2.3
    ],
    [
      6.3,
      3.4,
      5.6,
      2.4
    ],
    [
      4.8,
      3.4,
      1.9,
      0.2
    ],
    [
      5.8,
      2.7,
      5.1,
      1.9
    ],
    [
      7.2,
      3.0,
      5.8,
      1.6
    ],
    [
      5.4,
      3.9,
      1.7,
      0.4
    ],
    [
      6.9,
      3.2,
      5.7,
      2.3
    ],
    [
      6.5,
      3.0,
      5.5,
      1.8
    ],
    [
      7.7,
      2.6,
      6.9,
      2.3
    ],
    [
      6.4,
      3.1,
      5.5,
      1.8
    ],
    [
      5.2,
      3.5,
      1.5,
      0.2
    ],
    [
      6.3,
      2.9,
      5.6,
      1.8
    ],
    [
      4.9,
      3.1,
      1.5,
      0.2
    ],
    [
      7.9,
      3.8,
      6.4,
      2.0
    ],
    [
      5.5,
      4.2,
      1.4,
      0.2
    ],
    [
      6.1,
      3.0,
      4.9,
      1.8
    ],
    [
      5.0,
      3.2,
      1.2,
      0.2
    ],
    [
      4.9,
      3.0,
      1.4,
      0.2
    ],
    [
      6.0,
      2.2,
      4.0,
      1.0
    ],
    [
      5.0,
      3.6,
      1.4,
      0.2
    ],
    [
      4.6,
      3.4,
      1.4,
      0.3
    ],
    [
      6.9,
      3.1,
      5.1,
      2.3
    ],
    [
      5.0,
      3.5,
      1.3,
      0.3
    ],
    [
      5.8,
      2.8,
      5.1,
      2.4
    ],
    [
      4.9,
      3.1,
      1.5,
      0.1
    ],
    [
      5.6,
      2.7,
      4.2,
      1.3
    ],
    [
      7.0,
      3.2,
      4.7,
      1.4
    ],
    [
      6.3,
      2.7,
      4.9,
      1.8
    ],
    [
      5.0,
      3.4,
      1.5,
      0.2
    ],
    [
      5.8,
      2.7,
      5.1,
      1.9
    ],
    [
      6.1,
      2.9,
      4.7,
      1.4
    ],
    [
      7.2,
      3.6,
      6.1,
      2.5
    ],
    [
      6.7,
      3.1,
      5.6,
      2.4
    ],
    [
      6.3,
      3.3,
      6.0,
      2.5
    ],
    [
      6.3,
      2.5,
      4.9,
      1.5
    ],
    [
      4.8,
      3.1,
      1.6,
      0.2
    ],
    [
      6.4,
      2.8,
      5.6,
      2.1
    ],
    [
      6.2,
      2.9,
      4.3,
      1.3
    ],
    [
      5.7,
      2.5,
      5.0,
      2.0
    ],
    [
      6.0,
      3.4,
      4.5,
      1.6
    ],
    [
      5.2,
      3.4,
      1.4,
      0.2
    ],
    [
      5.7,
      4.4,
      1.5,
      0.4
    ],
    [
      5.0,
      2.3,
      3.3,
      1.0
    ],
    [
      6.2,
      2.2,
      4.5,
      1.5
    ],
    [
      6.3,
      2.3,
      4.4,
      1.3
    ],
    [
      6.3,
      2.8,
      5.1,
      1.5
    ],
    [
      5.1,
      3.3,
      1.7,
      0.5
    ],
    [
      6.0,
      2.9,
      4.5,
      1.5
    ],
    [
      6.5,
      3.0,
      5.2,
      2.0
    ],
    [
      5.3,
      3.7,
      1.5,
      0.2
    ],
    [
      6.8,
      2.8,
      4.8,
      1.4
    ],
    [
      5.9,
      3.0,
      5.1,
      1.8
    ],
    [
      4.7,
      3.2,
      1.6,
      0.2
    ],
    [
      5.5,
      3.5,
      1.3,
      0.2
    ],
    [
      6.7,
      3.0,
      5.2,
      2.3
    ],
    [
      5.7,
      2.6,
      3.5,
      1.0
    ],
    [
      5.8,
      2.7,
      4.1,
      1.0
    ],
    [
      5.5,
      2.5,
      4.0,
      1.3
    ],
    [
      5.1,
      3.8,
      1.9,
      0.4
    ],
    [
      5.7,
      2.8,
      4.5,
      1.3
    ],
    [
      6.7,
      3.1,
      4.4,
      1.4
    ],
    [
      6.4,
      3.2,
      5.3,
      2.3
    ],
    [
      7.7,
      2.8,
      6.7,
      2.0
    ],
    [
      5.5,
      2.6,
      4.4,
      1.2
    ],
    [
      5.7,
      2.9,
      4.2,
      1.3
    ],
    [
      7.4,
      2.8,
      6.1,
      1.9
    ],
    [
      7.6,
      3.0,
      6.6,
      2.1
    ],
    [
      6.3,
      3.3,
      4.7,
      1.6
    ],
    [
      5.4,
      3.0,
      4.5,
      1.5
    ],
    [
      6.2,
      2.8,
      4.8,
      1.8
    ],
    [
      4.4,
      3.2,
      1.3,
      0.2
    ],
    [
      6.6,
      2.9,
      4.6,
      1.3
    ],
    [
      7.2,
      3.2,
      6.0,
      1.8
    ],
    [
      4.7,
      3.2,
      1.3,
      0.2
    ],
    [
      5.7,
      2.8,
      4.1,
      1.3
    ],
    [
      5.5,
      2.3,
      4.0,
      1.3
    ],
    [
      5.1,
      3.8,
      1.5,
      0.3
    ],
    [
      6.1,
      2.6,
      5.6,
      1.4
    ],
    [
      4.6,
      3.2,
      1.4,
      0.2
    ],
    [
      6.7,
      3.3,
      5.7,
      2.1
    ],
    [
      6.7,
      3.1,
      4.7,
      1.5
    ],
    [
      5.6,
      2.5,
      3.9,
      1.1
    ],
    [
      5.1,
      3.5,
      1.4,
      0.2
    ],
    [
      5.0,
      3.4,
      1.6,
      0.4
    ],
    [
      5.1,
      3.5,
      1.4,
      0.3
    ],
    [
      4.8,
      3.0,
      1.4,
      0.1
    ],
    [
      6.1,
      2.8,
      4.7,
      1.2
    ],
    [
      5.9,
      3.0,
      4.2,
      1.5
    ],
    [
      5.0,
      3.5,
      1.6,
      0.6
    ],
    [
      6.1,
      3.0,
      4.6,
      1.4
    ],
    [
      6.8,
      3.0,
      5.5,
      2.1
    ],
    [
      5.1,
      3.8,
      1.6,
      0.2
    ],
    [
      5.7,
      3.0,
      4.2,
      1.2
    ],
    [
      4.4,
      2.9,
      1.4,
      0.2
    ],
    [
      4.4,
      3.0,
      1.3,
      0.2
    ],
    [
      5.4,
      3.4,
      1.5,
      0.4
    ],
    [
      7.7,
      3.8,
      6.7,
      2.2
    ],
    [
      5.0,
      2.0,
      3.5,
      1.0
    ],
    [
      6.4,
      2.9,
      4.3,
      1.3
    ],
    [
      6.0,
      2.2,
      5.0,
      1.5
    ],
    [
      4.6,
      3.1,
      1.5,
      0.2
    ],
    [
      5.8,
      2.7,
      3.9,
      1.2
    ],
    [
      4.9,
      2.5,
      4.5,
      1.7
    ],
    [
      4.8,
      3.0,
      1.4,
      0.3
    ],
    [
      5.4,
      3.9,
      1.3,
      0.4
    ],
    [
      6.4,
      3.2,
      4.5,
      1.5
    ],
    [
      6.3,
      2.5,
      5.0,
      1.9
    ]
  ]
}"""

# Validate the serving payload works on the model
validate_serving_input(model_uri, serving_payload)

array([0, 0, 1, 0, 2, 2, 1, 2, 0, 0, 0, 0, 2, 2, 2, 0, 2, 2, 0, 2, 2, 2,
       2, 0, 2, 0, 2, 0, 2, 0, 0, 1, 0, 0, 2, 0, 2, 0, 1, 1, 2, 0, 2, 1,
       2, 2, 2, 1, 0, 2, 1, 2, 1, 0, 0, 1, 1, 1, 2, 0, 1, 2, 0, 1, 2, 0,
       0, 2, 1, 1, 1, 0, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 2, 0, 1, 2, 0, 1,
       1, 0, 2, 0, 2, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 2, 0, 1, 0, 0, 0, 2,
       1, 1, 2, 0, 1, 2, 0, 0, 1, 2])

## Load the modeel back for prediction as a generic python function model 

In [15]:
loaded_model = mlflow.pyfunc.load_model(model_info.model_uri)

prediction = loaded_model.predict(X_test)

iris_features_name = datasets.load_iris().feature_names

result = pd.DataFrame(X_test, columns=iris_features_name)

result['actual_class'] = y_test
result['predicted_class'] = prediction

result[:7]

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                6.5               2.8                4.6               1.5   
1                5.9               3.0                5.1               1.8   
2                5.7               3.0                4.2               1.2   
3                4.6               3.6                1.0               0.2   
4                6.2               2.9                4.3               1.3   
5                6.0               3.4                4.5               1.6   
6                6.3               2.3                4.4               1.3   

   actual_class  predicted_class  
0             1                1  
1             2                2  
2             1                1  
3             0                0  
4             1                1  
5             1                1  
6             1                1

### Model Registry

The MLflow Model Registry component is a centralized model store, set of APIs, and UI, to collaboratively manage the full lifecycle of an MLflow Model. It provides model lineage (which MLflow experiment and run produced the model), model versioning, model aliasing, model tagging, and annotations.

In [16]:
### MLFLOW tracking

mlflow.set_tracking_uri(uri = "http://127.0.0.1:5000")

## Create a new MLflow experiment
mlflow.set_experiment("Iris_Classification")

## Start a MLFlow run and log the model
with mlflow.start_run():
    ## Log the hyperparameters
    mlflow.log_params(params)

    ## log the accuracy metrix
    mlflow.log_metric("accuracy", 1.0)

    ## Set a tag that we can use to remind ourselves what this run was for
    mlflow.set_tag("Training Info2", "Basic LR model for Iris Classification")
    
    ## Infer the model signature
    signature = infer_signature(X_train, lr.predict(X_train))

    ## Log the model
    model_info = mlflow.sklearn.log_model(
        sk_model = lr, 
        artifact_path = "Iris_Model",
        signature = signature,
        input_example = X_train,
    )

🏃 View run inquisitive-toad-453 at: http://127.0.0.1:5000/#/experiments/278257936357084962/runs/37b1787b6c8147088c4ae5a499ed234b
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/278257936357084962


In [19]:
## Inferencing from model from model registry 

import mlflow.sklearn
model_name = "tracking_iris_model"
model_version = "latest"

model_uri = f"models:/{model_name}/{model_version}"


model = mlflow.sklearn.load_model(model_uri)
model

LogisticRegression(max_iter=1000, multi_class='auto', random_state=1000,
                   solver='newton-cg')

In [20]:
model_uri

'models:/tracking_iris_model/latest'

In [22]:
y_pred_new = model.predict(X_test)
y_pred_new

array([1, 2, 1, 0, 1, 1, 1, 0, 1, 2, 0, 1, 0, 0, 2, 2, 2, 1, 2, 0, 2, 0,
       1, 1, 2, 1, 1, 2, 1, 1])